src/compra/urls.py
from django.conf.urls import url, include

from .views import *

urlpatterns = [
    # CRUD precio
    url(r'^compra/crear', CompraCreate.as_view(), name='compra_crear'),
    url(r'^compra/editar/(?P<pk>\d+)$', CompraUpdate.as_view(), name='compra_editar'),
    url(r'^compra/eliminar/(?P<pk>\d+)$', CompraDelete.as_view(), name='compra_eliminar'),
    url(r'^compra/lista', Compralist.as_view(), name='compra_lista'),
]

src/home/urls.py
from django.conf.urls import url

from .views import HomeTemplateView, dashboard, LoginTemplateView,grafico


urlpatterns = [
    #url(r'^$', HomeTemplateView.as_view(), name='index'),
    url(r'^$', dashboard, name='dashboard'),
    url(r'^grafico$', grafico, name='grafico'),
    url(r'^login$', LoginTemplateView.as_view(), name='login'),
]

src/precio/urls.py
from django.conf.urls import url, include
from .models import *
from .views import *
from .models import *
urlpatterns = [

    # CRUD precio
    url(r'^precio/crear', PrecioHistoricoCreate.as_view(), name='precio_crear'),
    url(r'^precio/editar/(?P<pk>\d+)$', PrecioHistoricoUpdate.as_view(), name='precio_editar'),
    url(r'^precio/eliminar/(?P<pk>\d+)$', PrecioHistoricoDelete.as_view(), name='precio_eliminar'),
    url(r'^precio/lista', PrecioHistoricoList.as_view(), name='precio_lista'),



]

src/reco/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    # url(r'^django-sb-admin/', include('django_sb_admin.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^', include('combustibles.urls', namespace="combustible")),
    url(r'^', include('precio.urls', namespace="precio")),
    url(r'^', include('handling.urls', namespace="handling")),
    url(r'^', include('venta.urls', namespace="venta")),
    url(r'^', include('compra.urls', namespace="compra")),
    url(r'^', include('users.urls', namespace="usuario")),
    url(r'^', include('reporte.urls', namespace="reporte")),
]

src/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^registrar', views.UserCreateView.as_view(), name="registrar"),
    url(r'^listar/', views.UserListView.as_view(), name="listar"),
    url(r'^editar/(?P<pk>[0-9]+)/$', views.UserUpdateView.as_view(), name='editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', views.UserDeleteView.as_view(), name="eliminar"),
    url(r'^password/(?P<pk>[0-9]+)/$', views.UserPasswordChangeView.as_view(), name='password'),


]

src/venta/urls.py
from django.conf.urls import url, include
from .models import *
from .views import *
from .models import *
urlpatterns = [

    # CRUD Ingreso de Combustibles
    # url(r'^venta/crear', VentaCreateView.as_view(), name='Venta_crear'),
     url(r'^venta/listar$', VentaList.as_view(), name="listar_venta"),
     url(r'^venta/crear$', CrearVenta.as_view(), name="crear_venta"),
     url(r'^venta/editar/(?P<pk>\d+)$', VentaUpdate.as_view(), name='venta_editar'),
     url(r'^venta/eliminar/(?P<pk>\d+)$', Deleteventa.as_view(), name='venta_delete'),
]

src/templates/base/lib/_main_footer.html
    {% block footer %}
    <div>
            <div class="pull-right">Creado por <strong>IPVG</strong>.</div>
            <div><strong>Copyright</strong> IPVG &copy; 2018</div>
    </div>
    {% endblock %}

src/templates/base/lib/_main_header.html
{% load i18n %}
<header>
    {% block nav_bar %}
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home:dashboard' %}">Reconciliación</a>
                </div>
                <!-- /.navbar-header -->
                <ul class="nav navbar-top-links navbar-right">
                    <!-- /.dropdown -->
                    {% block header_dropdowns %}
                        {% if request.user.is_authenticated %}
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            {% block user_footer %}
                            <li class="user-footer"><a href=""><i class="fa fa-user fa-fw"></i>{% firstof request.user.get_short_name request.user.get_username %}</a>
                            </li>
                            {% endblock %}
                            <li class="divider"></li>
                            <li><a href="{% url 'usuario:password' request.user.pk %}"><i class="fa fa-key fa-fw"></i>{% trans 'Change password' %}</a>
                            </li>
                            <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt fa-fw"></i> Cerrar Sesión</a>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                        {% endif %}
                    {% endblock header_dropdowns %}
                    <!-- /.dropdown -->
                </ul>
                <!-- /.navbar-top-links -->
                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">

                            <li>
                                <a href="#"><i class="fas fa-dollar-sign fa-fw"></i> Precios</a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="{% url 'precio:precio_crear' %}">Calcular</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'precio:precio_lista' %}">Ver Precios</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>

                            <li>
                                <a href="#"><i class="fas fa-shopping-cart fa-fw"></i> Abastecimiento de Combustible</a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="{% url 'compra:compra_crear' %}">Registro de Compra Combustible</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'compra:compra_lista' %}">Listar de Compras</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="#"><i class="fas fa-money-bill-alt fa-fw"></i> Arqueo de Ventas</a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="{% url 'venta:crear_venta' %}">Registrar Arqueo Venta</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'venta:listar_venta' %}">Lista De Arqueo de Ventas</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="#"><i class="fas fa-handshake fa-fw"></i> Registro Cliente Handling</a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="{% url 'handling:handlingCliente_crear' %}">Registrar Cliente Handling</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'handling:handlingCliente_list' %}">Listar Clientes Activos</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'handling:handlingCliente_listin' %}">Listar Clientes Inactivo</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="#"><i class="fas fa-hand-holding-usd fa-fw"></i> Handling Diario</a>
                                <ul class="nav nav-second-level">

                                    <li>
                                    <a href="#">Retiro</a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                        <a href="{% url 'handling:handlingDiario_crear' %}">Registrar Retiro Handling</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'handling:handlingDiario_list' %}">Historial de Retiros</a>
                                    </li>

                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                                    <li>
                                    <a href="#">Ingreso </a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                        <a href="{% url 'handling:ingresohandling_crear' %}">Registrar Ingreso Handling</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'handling:ingresohandling_list' %}">Historial de Ingresos</a>
                                    </li>

                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            {% if perms.auth.add_user %}
                            <li>
                                <a href="#"><i class="fa fa-users fa-fw"></i> Usuarios</a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="{% url 'usuario:registrar' %}">Registrar Usuario</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'usuario:listar' %}">Listar Usuario</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            {% endif %}
                            <li>
                                <a href="{% url 'reporte:reporte' %}"><i class="far fa-file-pdf fa-fw"></i> Reporte Compra-venta</a>
                                <a href="{% url 'reporte:hand' %}"><i class="far fa-file-pdf fa-fw"></i> Reporte retiros Handling</a>

                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
    </nav>
    {% endblock nav_bar %}
</header>

src/templates/base/lib/_scripts.html
{% load staticfiles %}

{% block scripts %}
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'vendor/metisMenu/metisMenu.min.js' %}"></script>

    <!-- Otros js -->
    <script src="{% static 'vendor/font-awesome/js/all.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>

    <script src="{% static 'js/anychart-base.min.js' %}"></script>
    <script src="{% static 'js/light_blue.min.js' %}"></script>
    <script src="{% static 'js/anychart-ui.min.js' %}"></script>
    <script src="{% static 'js/anychart-exports.min.js' %}"></script>
    <script src="{% static 'js/anychart-cartesian-3d.min.js' %}"></script>
    <!--nuevo-->
    <script src="{% static 'js/clipboard.min.js' %}"></script>
    <script src="https://cdn.anychart.com/releases/v8/js/anychart-data-adapter.min.js"></script>
    <script src="https://cdn.anychart.com/themes/v8/dark_blue.min.js"></script>
    <script src="https://cdn.anychart.com/releases/v8/locales/es-cl.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'dist/js/sb-admin-2.js' %}"></script>

    <script src="{% static 'js/plugins/prism/prism.min.js' %}"></script>
    <script id="js_common" src="{% static 'js/common.js' %}"></script>
{% endblock %}

src/templates/base/lib/_styles.html
{% load static %}

{% block styles %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'dist/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <link href="{% static 'vendor/font-awesome/css/all.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'dist/css/anychart-ui.min.css' %}" />

    <link rel="stylesheet" href="{% static 'dist/css/anychart-font.min.css' %}" />
    <!--nueva-->

    <link rel="stylesheet" href="{% static 'dist/css/app.min.css' %}" />
    <link rel="stylesheet" href="{% static 'dist/css/prism.coy.min.css' %}" />

{% endblock %}