src/home/urls.py
from django.conf.urls import url

from .views import HomeTemplateView, dashboard, LoginTemplateView,grafico


urlpatterns = [
    #url(r'^$', HomeTemplateView.as_view(), name='index'),
    url(r'^$', dashboard, name='dashboard'),
    url(r'^grafico$', grafico, name='grafico'),
    url(r'^login$', LoginTemplateView.as_view(), name='login'),
]

src/reco/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    # url(r'^django-sb-admin/', include('django_sb_admin.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^', include('combustibles.urls', namespace="combustible")),
    url(r'^', include('precio.urls', namespace="precio")),
    url(r'^', include('handling.urls', namespace="handling")),
    url(r'^', include('venta.urls', namespace="venta")),
    url(r'^', include('compra.urls', namespace="compra")),
    url(r'^', include('users.urls', namespace="usuario")),
    url(r'^', include('reporte.urls', namespace="reporte")),
]

src/venta/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from precio.models import *
from combustibles.models import *
import datetime
# Create your models here.


class Venta(models.Model):
    fecha = models.DateField(default= datetime.date.today)
    turno = models.CharField(max_length=2,choices=(('A', 'A'),('B', 'B')),default='A')
    precio = models.ForeignKey(PrecioHistorico, default=1)
    estado = models.CharField(max_length=8,choices=(('Activo', 'Activo'),('Inactivo', 'Inactivo')),default='Activo')


class DetalleVenta(models.Model):
    tot_venta_litro = models.DecimalField(max_digits=8, decimal_places=3, default=0, validators=[MaxValueValidator(10000), MinValueValidator(0)])
    combustible = models.ForeignKey('combustibles.Combustible')
    venta = models.ForeignKey(Venta)


class Arqueo(models.Model):
    tot_efectivo = models.IntegerField(default=0,verbose_name="Total Efectivo", validators=[MaxValueValidator(20000000), MinValueValidator(0)])
    cheque = models.IntegerField(default=0,verbose_name="Cheques", validators=[MaxValueValidator(20000000), MinValueValidator(0)])
    credito = models.IntegerField(default=0,verbose_name="Creditos", validators=[MaxValueValidator(20000000), MinValueValidator(0)])

    tarjecredebtbk = models.IntegerField(default=0,verbose_name="Tarjeta credito TBK", validators=[MaxValueValidator(20000000), MinValueValidator(0)])
    tarjedebtbk = models.IntegerField(default=0,verbose_name="Tarjeta debito TBK", validators=[MaxValueValidator(20000000), MinValueValidator(0)])
    subtotaltarje = models.IntegerField(verbose_name="Sub-Total Tarjetas", default=0)
    tot_ingreso = models.IntegerField(verbose_name="Total Ingreso", default=0)
    venta = models.ForeignKey(Venta,null=True,blank=True)

    def __str__(self):
        return self.tot_ingreso

src/templates/base/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
{% load i18n %}
<html lang="es">
<head>
    {% block meta %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% endblock %}

    <title>Reconciliación | {% block head_title %}Inicio{% endblock %}</title>

    {% block stylesheets %}
        {% include 'base/lib/_styles.html' %}
    {% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

    {{ form.media }}

</head>

<body>
    {% block body %}
    <div id="wrapper">
        {% block nav_header %}
            {% include 'base/lib/_main_header.html' %}
        {% endblock %}

        {% block content_wrapper %}
        <div class="content-wrapper" id="page-wrapper">
            {% block content_outer %}
            <section class="content">
                {% block content_block_wrap %}
                    {% block content %}{% endblock %}
                {% endblock %}
            </section>
            {% endblock content_outer %}
        </div>
        {% endblock content_wrapper %}

        {% block footer %}
        {% include 'base/lib/_main_footer.html' %}
        {% endblock %}

    </div>
    {% endblock body %}
{% block javascript %}
{% include 'base/lib/_scripts.html' %}
{% endblock %}

{% block extra_foot %}{% endblock %}
</body>
<script>
    $(document).ready(function() {
      $().ready(function() {

          $('#93').animateNumber({ number: '{{obj1.oc93}}' }, 1500);
          $('#95').animateNumber({ number: '{{obj1.oc95}}' }, 1500);
          $('#97').animateNumber({ number: '{{obj1.oc97}}' }, 1500);
          $('#diesel').animateNumber({ number: '{{obj1.diesel}}' }, 1500);

          anychart.onDocumentReady(function() {
          // create column chart
          grafica();
            });
          }); //no borrar
    });//no borrar
    function grafica(){
        $('#container-chart').html('<i class="fas fa-spinner fa-spin"></i>');
        console.log("graficando...");
        $('#container-chart').empty();
        anychart.onDocumentReady(function() {
          anychart.theme('Blue');
          // create column chart
          var chart = anychart.column3d();
          // turn on chart animation
          chart.animation(true);
          // set chart title text settings
          chart.title('Stock actual de combustibles');
          // create area series with passed data
          data = [
            ['93', '{{obj2.stock}}'],
            ['97', '{{obj3.stock}}'],
            ['Diesel', '{{obj4.stock}}']
          ]


          series = chart.column(data);
          series.fill(coloringFunction);
          function coloringFunction() {
            if (this.value <= 2000){
                return '#ff0000';
            }
            return this.sourceColor;
          }
          chart.tooltip()
            .position('center-top')
            .anchor('center-bottom')
            .offsetX(0)
            .offsetY(5)
            .format('{%Value} lts.');
          // set scale minimum
          chart.yScale().minimum(0);
          // set yAxis labels formatter
          chart.yAxis().labels().format('{%Value}{groupsSeparator: }');
          chart.tooltip().positionMode('point');
          chart.interactivity().hoverMode('by-x');
          chart.xAxis().title('Combustibles');
          chart.yAxis().title('Valores en litros');
          // set container id for the chart
          chart.container('container-chart');
          // initiate chart drawing
          chart.draw();
            });
    }

$("#id_tarjecredebtbk").bind('keyup mouseup', function () {
   $("#id_subtotaltarje").val(parseInt($("#id_tarjecredebtbk").val())+parseInt($("#id_tarjedebtbk").val()));
});
$("#id_tarjedebtbk").bind('keyup mouseup',function () {
   $("#id_subtotaltarje").val(parseInt($("#id_tarjecredebtbk").val())+parseInt($("#id_tarjedebtbk").val()));
});
$("#id_subtotaltarje").bind('change keydown paste input',function () {
   $("#id_tot_ingreso").val(parseInt($("#id_tot_efectivo").val())+parseInt($("#id_cheque").val())+parseInt($("#id_credito").val())+ parseInt($("#id_subtotaltarje").val()));
});

anychart.onDocumentReady(function () {
		var format ="MMMM yyyy";
		var locale = "es-cl";
		anychart.format.outputLocale("es-cl");
		anychart.format.outputDateTimeFormat("MMMM yyyy");
		var timeZoneOffset = new Date().getTimezoneOffset();
		var d = new Date();
		var a = d.getFullYear();
        var doce = d.getMonth();
        var once = d.getMonth()-10;
        var diez = d.getMonth()-9;
        var nueve = d.getMonth()-8;
        var ocho = d.getMonth()-7;
        var siete = d.getMonth()-6;
        var seis = d.getMonth()-5;
        var cinco = d.getMonth()-4;
        var cuatro = d.getMonth()-3;
        var tres = d.getMonth()-2;
        var dos = d.getMonth()-1;
        var uno = d.getMonth();
        var le = new Date(a, doce, 1);
        var lf = new Date(a, once, 0);
        var lm = new Date(a, diez, 0);
        var la = new Date(a, nueve, 0);
        var lma = new Date(a, ocho, 0);
        var lj = new Date(a, siete, 0);
        var lju = new Date(a, seis, 0);
        var lag = new Date(a, cinco, 0);
        var lse = new Date(a, cuatro, 0);
        var loc = new Date(a, tres, 0);
        var lno = new Date(a, dos, 0);
        var ldi = new Date(a, uno, 0);
		var data = [
            [lag, '{{obj8}}', '{{obj9}}', '{{obj10}}', '{{obj11}}'],
            [lse, '{{obj12}}', '{{obj13}}', '{{obj14}}', '{{obj15}}'],
            [loc, '{{obj16}}', '{{obj17}}', '{{obj18}}', '{{obj19}}'],
            [lno, '{{obj20}}', '{{obj21}}', '{{obj22}}', '{{obj23}}'],
            [ldi, '{{obj24}}', '{{obj25}}', '{{obj26}}', '{{obj27}}'],
            [le, '{{obj28}}', '{{obj29}}', '{{obj30}}', '{{obj31}}']
        ];

        var title = 'Ventas durante los últimos 6 meses\n' + 'Desde: ' +
            anychart.format.dateTime(data[0][0], format, timeZoneOffset, locale) +
            '\nHasta: ' + anychart.format.dateTime(data[data.length - 1][0], format, timeZoneOffset, locale);

        // Set a localization for output.
        anychart.format.outputLocale(locale);
        // create data set on our data, also we can put data directly to series
        var dataSet = anychart.data.set(data);

        // map data for the first series, take value from first column of data set
        var seriesData_1 = dataSet.mapAs({x: [0], value: [1]});

        // map data for the second series, take value from second column of data set
        var seriesData_2 = dataSet.mapAs({x: [0], value: [2]});

        // map data for the third series, take x from the zero column and value from the third column of data set
        var seriesData_3 = dataSet.mapAs({x: [0], value: [3]});

        var seriesData_4 = dataSet.mapAs({x: [0], value: [4]});

        // create line chart
        chart = anychart.line();
        // turn on the crosshair and tune it
        chart.crosshair()
            .enabled(true)
            .yLabel(false)
            .xLabel(false)
            .yStroke(null);
        // disable one of the chart grids
        chart.yGrid(0).enabled(false);
        // set chart title text settings
        chart.title(title).padding([20, 0, 10, 0]);
        // set yAxis title
        chart.yAxis().title('Ventas por mes');

        var seriesConfiguration = function (series, name) {
            series.name(name);
            series.hovered().markers()
                .enabled(true)
                .size(4);
        };

        // temp variable to store series instance
        var series;

        // setup first series
        series = chart.line(seriesData_1);
        series.stroke('#7CC0F7');
        seriesConfiguration(series, 'Total Litros 93 Vendidos');

        // setup second series
        series = chart.line(seriesData_2);
        series.stroke('#3C8AD8');
        seriesConfiguration(series, 'Total Litros 95 Vendidos');

        // setup third series
        series = chart.line(seriesData_3);
        series.stroke('#F18126');
        seriesConfiguration(series, 'Total Litros 97 Vendidos');

        // setup fourth series
        series = chart.line(seriesData_4);
        series.stroke('#f13b4e');
        seriesConfiguration(series, 'Total Litros Diesel Vendidos');

        // turn the legend on
        chart.legend().enabled(true).padding([0, 0, 10, 0]);

        chart.xAxis().labels().format(function () {
            return anychart.format.dateTime(this.value, 'MMM', timeZoneOffset, locale);
        });
        chart.tooltip().titleFormat(function () {
            return anychart.format.dateTime(this.points[0].x, format, timeZoneOffset, locale);
        });

        chart.tooltip().displayMode('union');

        // set container id for the chart
        chart.container(container);
        // initiate chart drawing
        chart.draw();
		});

</script>
</html>

src/templates/base/index.html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="refresh" content="0;url=pages/index.html">
<title>SB Admin 2</title>
<script language="javascript">
    window.location.href = "pages/index.html"
</script>
</head>
<body>
Go to <a href="pages/index.html">/pages/index.html</a>
</body>
</html>